language: node_js
sudo: false
node_js:
- '5'
git:
  depth: 3
branches:
  only:
    - master
    - /^release-.*$/
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
after_success:
  - npm run yolo
